// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDckBnlt3K4njiFrFVffbfjgLQF9XIEStE',
    appId: '1:510274941064:web:5073bedd2a01fef799af3d',
    messagingSenderId: '510274941064',
    projectId: 'citiguide-76a32',
    authDomain: 'citiguide-76a32.firebaseapp.com',
    storageBucket: 'citiguide-76a32.firebasestorage.app',
    measurementId: 'G-8NVFFX142J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP_-vxNg5eq9HatP7QLQcw5Ccz_DSwvYY',
    appId: '1:510274941064:android:79c4aec2c2a96db099af3d',
    messagingSenderId: '510274941064',
    projectId: 'citiguide-76a32',
    storageBucket: 'citiguide-76a32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFr-8C3eWI4WopivnJV_Ri4PdqOXXRMKo',
    appId: '1:510274941064:ios:b1e4dfd67d67932d99af3d',
    messagingSenderId: '510274941064',
    projectId: 'citiguide-76a32',
    storageBucket: 'citiguide-76a32.firebasestorage.app',
    iosBundleId: 'com.example.citiguideAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFr-8C3eWI4WopivnJV_Ri4PdqOXXRMKo',
    appId: '1:510274941064:ios:b1e4dfd67d67932d99af3d',
    messagingSenderId: '510274941064',
    projectId: 'citiguide-76a32',
    storageBucket: 'citiguide-76a32.firebasestorage.app',
    iosBundleId: 'com.example.citiguideAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDckBnlt3K4njiFrFVffbfjgLQF9XIEStE',
    appId: '1:510274941064:web:bd3e3ba57c5e251899af3d',
    messagingSenderId: '510274941064',
    projectId: 'citiguide-76a32',
    authDomain: 'citiguide-76a32.firebaseapp.com',
    storageBucket: 'citiguide-76a32.firebasestorage.app',
    measurementId: 'G-YS6R3PH5D6',
  );
}
